<?php  

include 'sidebarchemist.php';

?>

<div id="heads">
  <div class="container ">
  <ul class="col-sm-12">
  <li><a  href="INDEXlab.php" data-bs-toggle="tooltip" title="Display LAB" data-bs-placement="bottom"><i class="fa fa-home" aria-hidden="true"></i>Display STORE</a></li>
  <li><a href="InsertLAB.php" data-bs-toggle="tooltip" title="Add LAB" data-bs-placement="bottom"><i class="fa fa-folder-plus" aria-hidden="true"></i>Add STORE</a></li>
  <li><a href="UpdateTEST.php" data-bs-toggle="tooltip" title="Update LAB" data-bs-placement="bottom"><i class="fa fa-edit" aria-hidden="true"></i>Update STORE</a></li>
</ul>    
  </div>
  </div>


  <?php 
include 'footer.php';
?>